---

- hosts: all
  remote_user: root
  roles: 
  - role: common 

- hosts: controller
  remote_user: root
  roles:
    - haproxy
    - mariadb
    - rabbitmq
    - keystone
    - glance
    - cinder
    - nova
    - neutron
    - dashboard
    - swift
    - heat

- hosts: computes
  remote_user: root
  roles:
   - nova-compute
   - cinder-volume
   - neutron-compute


- hosts: swift-storage
  remote_user: root
  roles:
   - swift-storage



