---

- name: Install nova compute packages
  apt: name={{ item }} state=installed force=yes
  with_items:
   - nova-compute
   - sysfsutils

- name: Configure nova
  template: src=nova.j2 dest=/etc/nova/nova.conf
  notify:
   - restart nova-compute
  changed_when: true

- meta: flush_handlers
 





